apiVersion: apps/v1
kind: Deployment
metadata:
  name: hindalcofe-deployment
  # namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hcorptech/hindalcofrontend:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://api.hindalco.headsupcorporation.com" # Adjust this to your API gateway service name
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  # namespace: demo
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
  type: LoadBalancer
