global:
  configMapName: hindalcodevfe-configmap

deploymentName: hindalcofe-deployment
serviceName: hindalcofe
appLabel: hindalcofe
appName: hindalcofe
replicaCount: 1

image:
  repository: hcorptech/hindalcofrontend
  tag: 0.0.1
  pullPolicy: Always  # Force re-pull

# Add this to ensure correct architecture
nodeSelector:
  kubernetes.io/arch: amd64

containerPort: 3000  # Fixed port mismatch

service:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000  # Match container port
    protocol: TCP

resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "768Mi"

# Feature flags
appname_enabled: true
profile_enabled: false
discovery_enable: false
mongo_host_enable: false
jwt_enable: false